// <auto-generated />
using System;
using BusinessObject.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessObject.Migrations
{
    [DbContext(typeof(MyPhoneDbContext))]
    partial class MyPhoneDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObject.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DayOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("AccountId");

                    b.HasIndex("RoleId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            Address = "Quảng Bình",
                            DayOfBirth = new DateTime(2003, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tuannm23.dev@gmail.com",
                            FullName = "Nguyễn Minh Tuấn",
                            Gender = true,
                            Password = "1231234",
                            PhoneNumber = "0941673660",
                            RoleId = 2
                        },
                        new
                        {
                            AccountId = 2,
                            Address = "Quảng Nam",
                            DayOfBirth = new DateTime(2003, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tramy123@gmail.com",
                            FullName = "Phan Thị Trà My",
                            Gender = false,
                            Password = "123qwe",
                            PhoneNumber = "012345678",
                            RoleId = 2
                        },
                        new
                        {
                            AccountId = 3,
                            Address = "Quảng Nam",
                            DayOfBirth = new DateTime(2003, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "vinhthinh321@gmail.com",
                            FullName = "Trương Vĩnh Thịnh",
                            Gender = true,
                            Password = "123456",
                            PhoneNumber = "0987651431",
                            RoleId = 2
                        },
                        new
                        {
                            AccountId = 4,
                            Address = "Hà Nội",
                            DayOfBirth = new DateTime(1995, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "thanhhai456@gmail.com",
                            FullName = "Nguyễn Thanh Hải",
                            Gender = true,
                            Password = "abcdef",
                            PhoneNumber = "0978123456",
                            RoleId = 1
                        },
                        new
                        {
                            AccountId = 5,
                            Address = "Đà Nẵng",
                            DayOfBirth = new DateTime(1988, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maipham88@gmail.com",
                            FullName = "Phạm Thị Mai",
                            Gender = false,
                            Password = "xyz789",
                            PhoneNumber = "0967123123",
                            RoleId = 1
                        },
                        new
                        {
                            AccountId = 6,
                            Address = "Hồ Chí Minh",
                            DayOfBirth = new DateTime(1990, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hoatran90@gmail.com",
                            FullName = "Trần Thị Hoa",
                            Gender = false,
                            Password = "qwerty",
                            PhoneNumber = "0909123456",
                            RoleId = 1
                        },
                        new
                        {
                            AccountId = 7,
                            Address = "Bình Dương",
                            DayOfBirth = new DateTime(1987, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tamle87@gmail.com",
                            FullName = "Lê Văn Tâm",
                            Gender = true,
                            Password = "pass123",
                            PhoneNumber = "0918234567",
                            RoleId = 1
                        },
                        new
                        {
                            AccountId = 8,
                            Address = "Vĩnh Long",
                            DayOfBirth = new DateTime(1993, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tramnguyen93@gmail.com",
                            FullName = "Nguyễn Thị Ngọc Trâm",
                            Gender = false,
                            Password = "abc123",
                            PhoneNumber = "0987123456",
                            RoleId = 1
                        },
                        new
                        {
                            AccountId = 9,
                            Address = "Đắk Lắk",
                            DayOfBirth = new DateTime(1985, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ducphan85@gmail.com",
                            FullName = "Phan Văn Đức",
                            Gender = true,
                            Password = "abcd123",
                            PhoneNumber = "0978123456",
                            RoleId = 1
                        },
                        new
                        {
                            AccountId = 10,
                            Address = "Bắc Giang",
                            DayOfBirth = new DateTime(1996, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "binhnguyen96@gmail.com",
                            FullName = "Nguyễn Thị Bình",
                            Gender = false,
                            Password = "pass456",
                            PhoneNumber = "0987123123",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("BusinessObject.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Iphone"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Samsung"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Xiaomi"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Oppo"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Sony"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Realme"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "VSmart"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Vivo"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "One Plus"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Nokia"
                        });
                });

            modelBuilder.Entity("BusinessObject.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OrderId");

                    b.HasIndex("AccountId");

                    b.ToTable("Orders", t =>
                        {
                            t.HasCheckConstraint("CK_Order_Status", "[OrderStatus] = 'Pending' OR [OrderStatus] = 'Confirmed' OR [OrderStatus] = 'Cancelled'");
                        });

                    b.HasData(
                        new
                        {
                            OrderId = "O0001",
                            AccountId = 4,
                            OrderDate = new DateTime(2024, 7, 18, 4, 10, 8, 50, DateTimeKind.Local).AddTicks(197),
                            OrderStatus = "Confirmed"
                        },
                        new
                        {
                            OrderId = "O0002",
                            AccountId = 10,
                            OrderDate = new DateTime(2024, 7, 18, 4, 10, 8, 50, DateTimeKind.Local).AddTicks(218),
                            OrderStatus = "Pending"
                        },
                        new
                        {
                            OrderId = "O0003",
                            AccountId = 4,
                            OrderDate = new DateTime(2024, 7, 18, 4, 10, 8, 50, DateTimeKind.Local).AddTicks(220),
                            OrderStatus = "Cancelled"
                        },
                        new
                        {
                            OrderId = "O0004",
                            AccountId = 9,
                            OrderDate = new DateTime(2024, 7, 18, 4, 10, 8, 50, DateTimeKind.Local).AddTicks(222),
                            OrderStatus = "Confirmed"
                        },
                        new
                        {
                            OrderId = "O0005",
                            AccountId = 8,
                            OrderDate = new DateTime(2024, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Pending"
                        },
                        new
                        {
                            OrderId = "O0006",
                            AccountId = 4,
                            OrderDate = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderStatus = "Confirmed"
                        },
                        new
                        {
                            OrderId = "O0007",
                            AccountId = 5,
                            OrderDate = new DateTime(2024, 7, 18, 4, 10, 8, 50, DateTimeKind.Local).AddTicks(226),
                            OrderStatus = "Pending"
                        });
                });

            modelBuilder.Entity("BusinessObject.OrderDetail", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("ProductPhoneId")
                        .HasColumnType("nvarchar(7)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("money");

                    b.HasKey("OrderId", "ProductPhoneId");

                    b.HasIndex("ProductPhoneId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderId = "O0001",
                            ProductPhoneId = "P1001",
                            Quantity = 2,
                            TotalPrice = 69998m
                        },
                        new
                        {
                            OrderId = "O0001",
                            ProductPhoneId = "P2002",
                            Quantity = 1,
                            TotalPrice = 20459m
                        },
                        new
                        {
                            OrderId = "O0002",
                            ProductPhoneId = "P3001",
                            Quantity = 3,
                            TotalPrice = 44997m
                        },
                        new
                        {
                            OrderId = "O0003",
                            ProductPhoneId = "P4003",
                            Quantity = 1,
                            TotalPrice = 41990m
                        },
                        new
                        {
                            OrderId = "O0004",
                            ProductPhoneId = "P5003",
                            Quantity = 4,
                            TotalPrice = 79996m
                        },
                        new
                        {
                            OrderId = "O0005",
                            ProductPhoneId = "P1003",
                            Quantity = 3,
                            TotalPrice = 51000m
                        },
                        new
                        {
                            OrderId = "O0006",
                            ProductPhoneId = "P2001",
                            Quantity = 2,
                            TotalPrice = 59998m
                        },
                        new
                        {
                            OrderId = "O0007",
                            ProductPhoneId = "P3002",
                            Quantity = 1,
                            TotalPrice = 5999m
                        });
                });

            modelBuilder.Entity("BusinessObject.Product", b =>
                {
                    b.Property<string>("ProductPhoneId")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("MemoryPhone")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("PhoneDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("PhonePrice")
                        .HasColumnType("money");

                    b.Property<int>("PhoneQuantity")
                        .HasColumnType("int");

                    b.Property<string>("ProductPhoneName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RamPhone")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("ProductPhoneId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductPhoneId = "P1001",
                            CategoryId = 1,
                            MemoryPhone = "256 GB",
                            PhoneDescription = "The Iphone 14 Pro Max is the latest flagship model from Apple, featuring advanced camera systems, a stunning Super Retina XDR display, and the powerful A16 Bionic chip.",
                            PhonePrice = 34575000m,
                            PhoneQuantity = 25,
                            ProductPhoneName = "Iphone 14 Pro Max",
                            RamPhone = "16 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P1002",
                            CategoryId = 1,
                            MemoryPhone = "256 GB",
                            PhoneDescription = "The Iphone 13 brings a blend of style and performance with its sleek design, powerful A15 Bionic chip, and impressive camera system, making it a perfect choice for those seeking cutting-edge technology.",
                            PhonePrice = 24650m,
                            PhoneQuantity = 45,
                            ProductPhoneName = "Iphone 13",
                            RamPhone = "8 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P1003",
                            CategoryId = 1,
                            MemoryPhone = "256 GB",
                            PhoneDescription = "The Iphone XS Max features a large Super Retina OLED display, dual-camera system with Smart HDR, and Face ID for secure authentication, offering an exceptional experience for users.",
                            PhonePrice = 17000m,
                            PhoneQuantity = 105,
                            ProductPhoneName = "Iphone XS Max",
                            RamPhone = "8 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P1004",
                            CategoryId = 1,
                            MemoryPhone = "64 GB",
                            PhoneDescription = "The Iphone 8 Plus combines powerful performance with a classic design. It features a dual-camera system, A11 Bionic chip, and Retina HD display, offering a reliable and efficient user experience.",
                            PhonePrice = 7080m,
                            PhoneQuantity = 155,
                            ProductPhoneName = "Iphone 8 Plus",
                            RamPhone = "6 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P1005",
                            CategoryId = 1,
                            MemoryPhone = "128 GB",
                            PhoneDescription = "The Iphone 11 Pro sets new standards with its triple-camera system, Super Retina XDR display, and A13 Bionic chip. It delivers exceptional performance and capabilities, making it ideal for photography enthusiasts and power users.",
                            PhonePrice = 11575m,
                            PhoneQuantity = 85,
                            ProductPhoneName = "Iphone 11 Pro",
                            RamPhone = "6 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P2001",
                            CategoryId = 2,
                            MemoryPhone = "512 GB",
                            PhoneDescription = "The Samsung Galaxy S24 Ultra is the pinnacle of Samsung's smartphone technology, featuring a stunning Dynamic AMOLED 2X display, powerful Exynos 2200 processor, and versatile quad-camera system with 100x Space Zoom.",
                            PhonePrice = 29999m,
                            PhoneQuantity = 10,
                            ProductPhoneName = "Samsung Galaxy S24 Ultra",
                            RamPhone = "16 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P2002",
                            CategoryId = 2,
                            MemoryPhone = "128 GB",
                            PhoneDescription = "The Samsung Galaxy Z Flip5 combines cutting-edge foldable technology with a sleek design. It features a foldable Dynamic AMOLED display, Snapdragon 8 Gen 2 processor, and innovative Flex mode for enhanced user experience.",
                            PhonePrice = 20459m,
                            PhoneQuantity = 80,
                            ProductPhoneName = "Samsung Galaxy Z Flip5",
                            RamPhone = "12 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P2003",
                            CategoryId = 2,
                            MemoryPhone = "256 GB",
                            PhoneDescription = "The Samsung Galaxy S20 Plus offers a balance of performance and features. It includes a vibrant Super AMOLED display, versatile triple-camera setup, and powerful Exynos 990 processor for seamless multitasking.",
                            PhonePrice = 12999m,
                            PhoneQuantity = 190,
                            ProductPhoneName = "Samsung Galaxy S20 Plus",
                            RamPhone = "8 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P3001",
                            CategoryId = 3,
                            MemoryPhone = "128 GB",
                            PhoneDescription = "The Xiaomi POCO X6 Pro delivers exceptional value with its high-performance Snapdragon 870 processor, AMOLED display with 120Hz refresh rate, and quad-camera setup. ",
                            PhonePrice = 3540m,
                            PhoneQuantity = 170,
                            ProductPhoneName = "Xiaomi POCO X6 Pro",
                            RamPhone = "8 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P3002",
                            CategoryId = 3,
                            MemoryPhone = "512 GB",
                            PhoneDescription = "The Xiaomi Redmi 12 Turbo Edition is a budget-friendly smartphone that doesn't compromise on performance. It features a MediaTek Helio G88 processor, large display, and a versatile camera system, making it ideal for everyday use.",
                            PhonePrice = 8999m,
                            PhoneQuantity = 40,
                            ProductPhoneName = "Xiaomi Redmi 12 Turbo Edition",
                            RamPhone = "12 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P3003",
                            CategoryId = 3,
                            MemoryPhone = "256 GB",
                            PhoneDescription = "The Xiaomi Mi 11 Lite combines style with performance, featuring a sleek design, AMOLED display, Snapdragon 732G processor, and triple-camera setup. It's designed for users who prioritize both aesthetics and functionality.",
                            PhonePrice = 7900m,
                            PhoneQuantity = 15,
                            ProductPhoneName = "Xiaomi Mi 11 Lite",
                            RamPhone = "8 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P4001",
                            CategoryId = 4,
                            MemoryPhone = "256 GB",
                            PhoneDescription = "The Oppo Reno11 F offers a seamless blend of design and performance. Featuring a stylish design, AMOLED display, powerful Snapdragon processor, and a versatile camera system, it is perfect for capturing moments and multitasking.",
                            PhonePrice = 8490m,
                            PhoneQuantity = 29,
                            ProductPhoneName = "Oppo Reno11 F",
                            RamPhone = "8 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P4002",
                            CategoryId = 4,
                            MemoryPhone = "512 GB",
                            PhoneDescription = "The Oppo Find X5 Pro is a flagship device designed for premium performance. It comes with a cutting-edge AMOLED display, advanced Snapdragon chipset, and a sophisticated camera system, making it ideal for photography enthusiasts.",
                            PhonePrice = 16490m,
                            PhoneQuantity = 75,
                            ProductPhoneName = "Oppo Find X5 Pro",
                            RamPhone = "8 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P4003",
                            CategoryId = 4,
                            MemoryPhone = "1 TB",
                            PhoneDescription = "The Oppo Find N3 stands out with its innovative design and top-tier features. It boasts a foldable AMOLED display, high-end Snapdragon processor, and a versatile camera array.",
                            PhonePrice = 41990m,
                            PhoneQuantity = 5,
                            ProductPhoneName = "Oppo Find N3",
                            RamPhone = "16 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P5001",
                            CategoryId = 5,
                            MemoryPhone = "512 GB",
                            PhoneDescription = "The Sony Xperia 1 IV is designed for creative professionals, featuring a 4K HDR OLED display, triple-camera system with ZEISS optics, and a powerful Snapdragon 8 Gen 1 processor. Ideal for photography and video enthusiasts.",
                            PhonePrice = 29990m,
                            PhoneQuantity = 50,
                            ProductPhoneName = "Sony Xperia 1 IV",
                            RamPhone = "8 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P5002",
                            CategoryId = 5,
                            MemoryPhone = "256 GB",
                            PhoneDescription = "The Sony Xperia 5 IV offers a compact yet powerful experience with its 6.1-inch OLED display, advanced camera system, and Snapdragon 8 Gen 1 processor. Perfect for users seeking a high-performance smartphone in a smaller form factor.",
                            PhonePrice = 24990m,
                            PhoneQuantity = 70,
                            ProductPhoneName = "Sony Xperia 5 IV",
                            RamPhone = "8 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P5003",
                            CategoryId = 5,
                            MemoryPhone = "256 GB",
                            PhoneDescription = "The Sony Xperia 10 IV combines style and functionality, featuring a 6-inch OLED display, triple-camera setup, and Snapdragon 690 processor. It offers excellent performance and battery life, making it suitable for everyday use.",
                            PhonePrice = 14990m,
                            PhoneQuantity = 90,
                            ProductPhoneName = "Sony Xperia 10 IV",
                            RamPhone = "8 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P6001",
                            CategoryId = 6,
                            MemoryPhone = "512 GB",
                            PhoneDescription = "The Realme GT 2 Pro is a high-performance smartphone featuring a Snapdragon 8 Gen 1 processor, 6.7-inch AMOLED display with a 120Hz refresh rate, and a triple-camera system. It's designed for users seeking top-tier specs and smooth performance.",
                            PhonePrice = 18999m,
                            PhoneQuantity = 65,
                            ProductPhoneName = "Realme GT 2 Pro",
                            RamPhone = "16 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P6002",
                            CategoryId = 6,
                            MemoryPhone = "512 GB",
                            PhoneDescription = "The Realme 9 Pro+ combines advanced features and affordability, offering a 6.4-inch Super AMOLED display, MediaTek Dimensity 920 processor, and a versatile triple-camera setup. It's perfect for those looking for a balance of performance and value.",
                            PhonePrice = 14999m,
                            PhoneQuantity = 80,
                            ProductPhoneName = "Realme 9 Pro+",
                            RamPhone = "16 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P6003",
                            CategoryId = 6,
                            MemoryPhone = "128 GB",
                            PhoneDescription = "The Realme C35 is an entry-level smartphone that doesn't compromise on essential features. It has a 6.6-inch IPS LCD display, Unisoc T616 processor, and a triple-camera system, providing reliable performance for everyday tasks.",
                            PhonePrice = 7999m,
                            PhoneQuantity = 120,
                            ProductPhoneName = "Realme C35",
                            RamPhone = "8 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P7001",
                            CategoryId = 7,
                            MemoryPhone = "256 GB",
                            PhoneDescription = "The VSmart Aris Pro features an innovative under-display camera, a 6.39-inch AMOLED display, Snapdragon 730 processor, and a quad-camera system. It's designed for users seeking cutting-edge technology and sleek design.",
                            PhonePrice = 13999m,
                            PhoneQuantity = 50,
                            ProductPhoneName = "VSmart Aris Pro",
                            RamPhone = "8 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P7002",
                            CategoryId = 7,
                            MemoryPhone = "128 GB",
                            PhoneDescription = "The VSmart Joy 4 is an affordable yet feature-packed smartphone with a 6.53-inch Full HD+ display, Snapdragon 665 processor, and a quad-camera setup. It's ideal for users looking for great value and performance.",
                            PhonePrice = 4999m,
                            PhoneQuantity = 75,
                            ProductPhoneName = "VSmart Joy 4",
                            RamPhone = "6 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P7003",
                            CategoryId = 7,
                            MemoryPhone = "128 GB",
                            PhoneDescription = "The VSmart Active 3 combines modern design and functionality, featuring a 6.39-inch AMOLED display, MediaTek Helio P60 processor, and a triple-camera system. It offers excellent performance and aesthetics for everyday use.",
                            PhonePrice = 7999m,
                            PhoneQuantity = 90,
                            ProductPhoneName = "VSmart Active 3",
                            RamPhone = "8 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P8001",
                            CategoryId = 8,
                            MemoryPhone = "256 GB",
                            PhoneDescription = "The Vivo X80 Pro offers a premium smartphone experience with its 6.78-inch AMOLED display, Snapdragon 8 Gen 1 processor, and advanced quad-camera system co-engineered with ZEISS.",
                            PhonePrice = 24999m,
                            PhoneQuantity = 40,
                            ProductPhoneName = "Vivo X80 Pro",
                            RamPhone = "8 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P8002",
                            CategoryId = 8,
                            MemoryPhone = "512 GB",
                            PhoneDescription = "The Vivo V23 5G combines style and innovation, featuring a 6.44-inch AMOLED display, MediaTek Dimensity 920 processor, and a dual front camera system with a 50MP main sensor.",
                            PhonePrice = 19999m,
                            PhoneQuantity = 60,
                            ProductPhoneName = "Vivo V23 5G",
                            RamPhone = "8 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P8003",
                            CategoryId = 8,
                            MemoryPhone = "256 GB",
                            PhoneDescription = "The Vivo Y75 is a versatile and affordable smartphone, boasting a 6.58-inch Full HD+ display, MediaTek Helio G96 processor, and a triple-camera setup.",
                            PhonePrice = 12999m,
                            PhoneQuantity = 100,
                            ProductPhoneName = "Vivo Y75",
                            RamPhone = "8 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P9001",
                            CategoryId = 9,
                            MemoryPhone = "1 TB",
                            PhoneDescription = "The OnePlus 10 Pro offers a flagship experience with its 6.7-inch Fluid AMOLED display, Snapdragon 8 Gen 1 processor, and Hasselblad-tuned triple-camera system.",
                            PhonePrice = 31999m,
                            PhoneQuantity = 50,
                            ProductPhoneName = "OnePlus 10 Pro",
                            RamPhone = "16 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P9002",
                            CategoryId = 9,
                            MemoryPhone = "512 GB",
                            PhoneDescription = "The OnePlus Nord 2T combines performance and affordability, featuring a 6.43-inch AMOLED display, MediaTek Dimensity 1300 processor, and a versatile triple-camera setup.",
                            PhonePrice = 19999m,
                            PhoneQuantity = 70,
                            ProductPhoneName = "OnePlus Nord 2T",
                            RamPhone = "8 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P9003",
                            CategoryId = 9,
                            MemoryPhone = "256 GB",
                            PhoneDescription = "The OnePlus 9R offers a premium experience with its 6.55-inch Fluid AMOLED display, Snapdragon 870 processor, and quad-camera system. It provides a smooth and responsive performance.",
                            PhonePrice = 24999m,
                            PhoneQuantity = 90,
                            ProductPhoneName = "OnePlus 9R",
                            RamPhone = "16 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P10001",
                            CategoryId = 10,
                            MemoryPhone = "512 GB",
                            PhoneDescription = "The Nokia X20 combines durability and performance with its 6.67-inch Full HD+ display, Snapdragon 480 5G processor, and quad-camera setup.",
                            PhonePrice = 15999m,
                            PhoneQuantity = 60,
                            ProductPhoneName = "Nokia X20",
                            RamPhone = "12 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P10002",
                            CategoryId = 10,
                            MemoryPhone = "256 GB",
                            PhoneDescription = "The Nokia G50 is an affordable 5G smartphone featuring a 6.82-inch HD+ display, Snapdragon 480 5G processor, and a triple-camera system.",
                            PhonePrice = 12999m,
                            PhoneQuantity = 80,
                            ProductPhoneName = "Nokia G50",
                            RamPhone = "12 GB"
                        },
                        new
                        {
                            ProductPhoneId = "P10003",
                            CategoryId = 10,
                            MemoryPhone = "512 GB",
                            PhoneDescription = "The Nokia 8.3 5G offers a premium experience with its 6.81-inch PureDisplay, Snapdragon 765G processor, and quad-camera system with ZEISS optics. It is designed for users who want cutting-edge technology and superior camera capabilities.",
                            PhonePrice = 22999m,
                            PhoneQuantity = 50,
                            ProductPhoneName = "Nokia 8.3 5G",
                            RamPhone = "16 GB"
                        });
                });

            modelBuilder.Entity("BusinessObject.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Customer"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Staff"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Administrator"
                        });
                });

            modelBuilder.Entity("BusinessObject.Account", b =>
                {
                    b.HasOne("BusinessObject.Role", "Role")
                        .WithMany("Account")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BusinessObject.Order", b =>
                {
                    b.HasOne("BusinessObject.Account", "Account")
                        .WithMany("Order")
                        .HasForeignKey("AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BusinessObject.OrderDetail", b =>
                {
                    b.HasOne("BusinessObject.Order", "Order")
                        .WithMany("OrderDetail")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Product", "Product")
                        .WithMany("OrderDetail")
                        .HasForeignKey("ProductPhoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BusinessObject.Product", b =>
                {
                    b.HasOne("BusinessObject.Category", "Category")
                        .WithMany("Product")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BusinessObject.Account", b =>
                {
                    b.Navigation("Order");
                });

            modelBuilder.Entity("BusinessObject.Category", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("BusinessObject.Order", b =>
                {
                    b.Navigation("OrderDetail");
                });

            modelBuilder.Entity("BusinessObject.Product", b =>
                {
                    b.Navigation("OrderDetail");
                });

            modelBuilder.Entity("BusinessObject.Role", b =>
                {
                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
